import React, { useState } from 'react';
import { 
  Download, 
  X, 
  Server, 
  FileCode, 
  Terminal, 
  CheckCircle2, 
  Copy, 
  ShieldCheck, 
  Zap, 
  ExternalLink,
  Archive,
  RefreshCw
} from 'lucide-react';
import { TradingBot, TradePosition } from '../types';

interface ExportProjectModalProps {
  isOpen: boolean;
  onClose: () => void;
  bots: TradingBot[];
  activeTrades: TradePosition[];
  auditLogs: TradePosition[];
}

export const ExportProjectModal: React.FC<ExportProjectModalProps> = ({
  isOpen,
  onClose,
  bots,
  activeTrades,
  auditLogs,
}) => {
  const [isDownloading, setIsDownloading] = useState(false);
  const [copiedSection, setCopiedSection] = useState<string | null>(null);

  if (!isOpen) return null;

  const handleDownloadZip = async () => {
    setIsDownloading(true);
    try {
      // Direct browser navigation to download the ZIP file generated by the backend
      const link = document.createElement('a');
      link.href = '/api/export-project-zip';
      link.download = 'nexus-five-trading-fleet.zip';
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    } catch (e) {
      console.error('Download error:', e);
    } finally {
      setTimeout(() => setIsDownloading(false), 1500);
    }
  };

  const handleCopy = (text: string, sectionId: string) => {
    navigator.clipboard.writeText(text);
    setCopiedSection(sectionId);
    setTimeout(() => setCopiedSection(null), 2000);
  };

  const vpsSetupScript = `# 1. Connect to VisiHost VPS
ssh root@YOUR_VISIHOST_IP

# 2. Install Node.js 20 & PM2 for 24/7 background uptime
sudo apt update && sudo apt upgrade -y
curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
sudo apt install -y nodejs git build-essential unzip
sudo npm install -g pm2

# 3. Create folder, extract ZIP, and install
mkdir -p /var/www/trading-fleet
cd /var/www/trading-fleet
# (Upload the downloaded nexus-five-trading-fleet.zip here)
unzip ~/nexus-five-trading-fleet.zip -d .
npm install

# 4. Configure .env credentials
cp .env.example .env
nano .env

# 5. Build and launch 24/7 background engine
npm run build
pm2 start ecosystem.config.cjs
pm2 startup
pm2 save

# 6. View live real-time trading logs
pm2 logs nexus-five-trading-fleet`;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-xs animate-in fade-in duration-200">
      <div 
        id="export-project-modal"
        className="bg-white border border-slate-200 rounded-2xl max-w-2xl w-full shadow-2xl overflow-hidden max-h-[92vh] flex flex-col"
      >
        {/* Header */}
        <div className="px-6 py-4 bg-gradient-to-r from-blue-900 via-indigo-900 to-slate-900 text-white flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-blue-500/20 border border-blue-400/30 flex items-center justify-center text-blue-300">
              <Archive className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-base sm:text-lg font-bold">Download Code & Deployment Kit</h2>
              <p className="text-xs text-blue-200">Export full project for 24/7 hosting on VisiHost / VPS</p>
            </div>
          </div>
          <button 
            onClick={onClose}
            className="p-1.5 text-slate-300 hover:text-white rounded-lg hover:bg-white/10 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Modal Content */}
        <div className="p-6 overflow-y-auto space-y-5 text-slate-700 text-sm">
          
          {/* Main Action Banner */}
          <div className="bg-gradient-to-br from-blue-50 to-indigo-50 border border-blue-200 rounded-2xl p-5 flex flex-col sm:flex-row items-center justify-between gap-4">
            <div className="space-y-1 text-center sm:text-left">
              <div className="flex items-center justify-center sm:justify-start gap-2">
                <span className="font-bold text-slate-900 text-base">nexus-five-trading-fleet.zip</span>
                <span className="px-2 py-0.5 text-[10px] font-bold bg-blue-100 text-blue-800 rounded-full border border-blue-200">
                  Ready to Host
                </span>
              </div>
              <p className="text-xs text-slate-600">
                Complete React + Express + 5-Bot Engine + Top 500 Scanner + PM2 configs & VisiHost guide.
              </p>
            </div>

            <button
              id="confirm-download-zip-btn"
              onClick={handleDownloadZip}
              disabled={isDownloading}
              className="w-full sm:w-auto px-5 py-3 bg-blue-600 hover:bg-blue-700 active:bg-blue-800 text-white font-bold rounded-xl shadow-md transition-all flex items-center justify-center gap-2 text-sm whitespace-nowrap cursor-pointer hover:shadow-lg active:scale-98 disabled:opacity-50"
            >
              {isDownloading ? (
                <>
                  <RefreshCw className="w-4 h-4 animate-spin" />
                  <span>Packaging ZIP...</span>
                </>
              ) : (
                <>
                  <Download className="w-4 h-4" />
                  <span>Download Project ZIP</span>
                </>
              )}
            </button>
          </div>

          {/* Included Package Contents */}
          <div className="border border-slate-200 rounded-xl p-4 bg-white">
            <div className="text-xs font-bold text-slate-900 uppercase tracking-wider mb-2.5 flex items-center gap-2">
              <FileCode className="w-4 h-4 text-indigo-600" />
              What is included in your ZIP:
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs text-slate-600">
              <div className="flex items-center gap-2">
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600 shrink-0" />
                <span>Full TypeScript source code (<code>/src</code>)</span>
              </div>
              <div className="flex items-center gap-2">
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600 shrink-0" />
                <span>Express backend & Binance ticker proxy (<code>server.ts</code>)</span>
              </div>
              <div className="flex items-center gap-2">
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600 shrink-0" />
                <span>PM2 24/7 production setup (<code>ecosystem.config.cjs</code>)</span>
              </div>
              <div className="flex items-center gap-2">
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600 shrink-0" />
                <span>One-click startup script (<code>start-visihost.sh</code>)</span>
              </div>
              <div className="flex items-center gap-2">
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600 shrink-0" />
                <span>VisiHost deployment instructions (<code>VISIHOST_DEPLOYMENT_GUIDE.md</code>)</span>
              </div>
              <div className="flex items-center gap-2">
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600 shrink-0" />
                <span>All 500 Coin dataset & Risk Rules</span>
              </div>
            </div>
          </div>

          {/* Quick VisiHost Command Guide */}
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <div className="text-xs font-bold text-slate-900 uppercase tracking-wider flex items-center gap-1.5">
                <Terminal className="w-4 h-4 text-blue-600" />
                VisiHost VPS 24/7 Setup Commands
              </div>
              <button
                onClick={() => handleCopy(vpsSetupScript, 'script')}
                className="text-xs text-blue-600 hover:text-blue-800 font-semibold flex items-center gap-1"
              >
                {copiedSection === 'script' ? (
                  <>
                    <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600" />
                    <span className="text-emerald-600">Copied!</span>
                  </>
                ) : (
                  <>
                    <Copy className="w-3.5 h-3.5" />
                    <span>Copy All Commands</span>
                  </>
                )}
              </button>
            </div>

            <div className="bg-slate-900 text-slate-200 p-4 rounded-xl font-mono text-xs overflow-x-auto max-h-48 scrollbar-thin border border-slate-800">
              <pre>{vpsSetupScript}</pre>
            </div>
          </div>

          {/* Additional Guidance */}
          <div className="bg-amber-50 border border-amber-200 rounded-xl p-3.5 text-xs text-amber-800 flex items-start gap-2.5">
            <ShieldCheck className="w-4 h-4 text-amber-600 shrink-0 mt-0.5" />
            <div>
              <strong>Security Reminder:</strong> When deploying to your VisiHost server, never share your <code>.env</code> file publicly. Enter your <code>GEMINI_API_KEY</code>, <code>TELEGRAM_BOT_TOKEN</code>, and <code>TELEGRAM_CHAT_ID</code> directly on your server.
            </div>
          </div>

        </div>

        {/* Footer */}
        <div className="px-6 py-4 bg-slate-50 border-t border-slate-200 flex items-center justify-between">
          <span className="text-xs text-slate-500">
            Current Fleet: 5 Bots | {activeTrades.length} Active Trades | {auditLogs.length} Logged
          </span>
          <div className="flex items-center gap-2">
            <button
              onClick={onClose}
              className="px-4 py-2 text-xs font-semibold text-slate-600 hover:text-slate-900 bg-white border border-slate-200 rounded-xl hover:bg-slate-50 transition-all"
            >
              Close
            </button>
            <button
              onClick={handleDownloadZip}
              className="px-4 py-2 text-xs font-bold text-white bg-blue-600 hover:bg-blue-700 rounded-xl shadow-xs transition-all flex items-center gap-1.5"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download ZIP</span>
            </button>
          </div>
        </div>

      </div>
    </div>
  );
};
